## **Many Glacier SNOTEL Station Dataset EDA**

In [176]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [177]:
dataset = pd.read_csv('GNP_SNOTEL_dataset_1986_2026.txt').set_index('Date')
dataset.head()

,Flattop Mtn. (482) Air Temperature Average (degF),Flattop Mtn. (482) Air Temperature Maximum (degF),Flattop Mtn. (482) Air Temperature Minimum (degF),Flattop Mtn. (482) Air Temperature Observed (degF) Start of Day Values,Flattop Mtn. (482) Snow Water Equivalent (in) Start of Day Values,Flattop Mtn. (482) Snow Depth (in) Start of Day Values,Many Glacier (613) Air Temperature Average (degF),Many Glacier (613) Air Temperature Maximum (degF),Many Glacier (613) Air Temperature Minimum (degF),Many Glacier (613) Air Temperature Observed (degF) Start of Day Values,Many Glacier (613) Snow Water Equivalent (in) Start of Day Values,Many Glacier (613) Snow Depth (in) Start of Day Values
Date,,,,,,,,,,,,
1986-01-01,21.0,23.9,18.0,20.5,18.0,NaN,NaN,NaN,NaN,24.8,3.7,NaN
1986-01-02,15.4,17.8,6.6,17.6,18.6,NaN,NaN,NaN,NaN,21.2,4.0,NaN
1986-01-03,11.8,19.0,2.3,16.5,19.1,NaN,NaN,NaN,NaN,16.7,4.3,NaN
1986-01-04,5.9,20.7,1.4,7.2,19.3,NaN,NaN,NaN,NaN,13.6,4.3,NaN
1986-01-05,15.4,24.4,3.6,7.2,19.3,NaN,NaN,NaN,NaN,26.4,4.3,NaN

## Flattop Mountain Dataset

In [178]:
flattop_data = dataset.iloc[:, :6]
flattop_data.head()

,Flattop Mtn. (482) Air Temperature Average (degF),Flattop Mtn. (482) Air Temperature Maximum (degF),Flattop Mtn. (482) Air Temperature Minimum (degF),Flattop Mtn. (482) Air Temperature Observed (degF) Start of Day Values,Flattop Mtn. (482) Snow Water Equivalent (in) Start of Day Values,Flattop Mtn. (482) Snow Depth (in) Start of Day Values
Date,,,,,,
1986-01-01,21.0,23.9,18.0,20.5,18.0,NaN
1986-01-02,15.4,17.8,6.6,17.6,18.6,NaN
1986-01-03,11.8,19.0,2.3,16.5,19.1,NaN
1986-01-04,5.9,20.7,1.4,7.2,19.3,NaN
1986-01-05,15.4,24.4,3.6,7.2,19.3,NaN

In [179]:
flattop_temp_data = flattop_data.iloc[:, :1].copy()
flattop_temp_data = flattop_temp_data.rename(columns={'Flattop Mtn. (482) Air Temperature Average (degF)': 'average_air_temp_F'})
flattop_temp_data.index = pd.to_datetime(flattop_temp_data.index)
flattop_temp_data

            average_air_temp_F
Date
1986-01-01                21.0
1986-01-02                15.4
1986-01-03                11.8
1986-01-04                 5.9
1986-01-05                15.4
...                        ...
2026-10-10                29.1
2026-10-11                22.3
2026-10-12                25.2
2026-10-13                28.4
2026-10-14                 NaN

[14897 rows x 1 columns]

In [180]:
print(flattop_temp_data.isna().sum(), '\n')
print(flattop_temp_data.info())

average_air_temp_F    448
dtype: int64

<class 'pandas.DataFrame'>
DatetimeIndex: 14897 entries, 1986-01-01 to 2026-10-14
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   average_air_temp_F  14449 non-null  float64
dtypes: float64(1)
memory usage: 232.8 KB
None

In [181]:
flattop_temp_data['average_air_temp_C'] = (flattop_temp_data['average_air_temp_F'] - 32) * 5/9
flattop_temp_data

            average_air_temp_F  average_air_temp_C
Date
1986-01-01                21.0           -6.111111
1986-01-02                15.4           -9.222222
1986-01-03                11.8          -11.222222
1986-01-04                 5.9          -14.500000
1986-01-05                15.4           -9.222222
...                        ...                 ...
2026-10-10                29.1           -1.611111
2026-10-11                22.3           -5.388889
2026-10-12                25.2           -3.777778
2026-10-13                28.4           -2.000000
2026-10-14                 NaN                 NaN

[14897 rows x 2 columns]

In [182]:
flattop_temp_data.to_csv('flattop_average_temps.csv', index=True)

## Many Glacier Dataset

In [183]:
many_glacier_data = dataset.iloc[:, 6:]
many_glacier_data.head()

,Many Glacier (613) Air Temperature Average (degF),Many Glacier (613) Air Temperature Maximum (degF),Many Glacier (613) Air Temperature Minimum (degF),Many Glacier (613) Air Temperature Observed (degF) Start of Day Values,Many Glacier (613) Snow Water Equivalent (in) Start of Day Values,Many Glacier (613) Snow Depth (in) Start of Day Values
Date,,,,,,
1986-01-01,NaN,NaN,NaN,24.8,3.7,NaN
1986-01-02,NaN,NaN,NaN,21.2,4.0,NaN
1986-01-03,NaN,NaN,NaN,16.7,4.3,NaN
1986-01-04,NaN,NaN,NaN,13.6,4.3,NaN
1986-01-05,NaN,NaN,NaN,26.4,4.3,NaN

In [184]:
many_glacier_temp_data = many_glacier_data.iloc[:, :1].copy()
many_glacier_temp_data = many_glacier_temp_data.rename(columns={'Many Glacier (613) Air Temperature Average (degF)':'average_air_temp_F'})
many_glacier_temp_data

            average_air_temp_F
Date
1986-01-01                 NaN
1986-01-02                 NaN
1986-01-03                 NaN
1986-01-04                 NaN
1986-01-05                 NaN
...                        ...
2026-10-10                 NaN
2026-10-11                 NaN
2026-10-12                 NaN
2026-10-13                 NaN
2026-10-14                 NaN

[14897 rows x 1 columns]

In [185]:
print(many_glacier_temp_data.isna().sum(), '\n')
print(many_glacier_temp_data.info())

average_air_temp_F    144
dtype: int64

<class 'pandas.DataFrame'>
Index: 14897 entries, 1986-01-01 to 2026-10-14
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   average_air_temp_F  14753 non-null  float64
dtypes: float64(1)
memory usage: 232.8+ KB
None

In [186]:
many_glacier_temp_data['average_air_temp_C'] = (many_glacier_temp_data['average_air_temp_F'] - 32) * 5/9
many_glacier_temp_data

            average_air_temp_F  average_air_temp_C
Date
1986-01-01                 NaN                 NaN
1986-01-02                 NaN                 NaN
1986-01-03                 NaN                 NaN
1986-01-04                 NaN                 NaN
1986-01-05                 NaN                 NaN
...                        ...                 ...
2026-10-10                 NaN                 NaN
2026-10-11                 NaN                 NaN
2026-10-12                 NaN                 NaN
2026-10-13                 NaN                 NaN
2026-10-14                 NaN                 NaN

[14897 rows x 2 columns]

In [187]:
many_glacier_temp_data.to_csv('manyglacier_average_temps.csv', index=True)